---
title: "hw5"
author: "Jiawei Ye"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

###Problem 1

#### Load and tidy data

```{r read_data}

longi_study = as.data.frame(list.files(path = "./data/problem1")) %>% 
  janitor::clean_names() %>% 
  rename(file_name = list_files_path_data_problem1)

read_data = function(csv_name){
  csv_name = str_c("./data/problem1/", as.character(csv_name))
  read.csv(csv_name)
}

longi_study = 
  add_column(longi_study, data = map(longi_study[[1]], read_data)) %>% 
  unnest()

##alternatively the code below gives the unnested result directly
#longi_study = bind_cols(longi_study, map_df(.x = longi_study[[1]], ~read_data(.x)))
```

Now tidy the data... a bit

```{r tidy_data}
longi_study =
  rename(longi_study, subject = file_name) %>% 
  mutate(subject = as.character(subject), 
         subject = str_trunc(subject, 6,  ellipsis = "")) %>% 
  separate(subject, into = c("group", "id"), remove = FALSE)
```

####Spaghetti plot

```{r plot}
longi_study %>% 
  gather(c(week_1:week_8), key = "week", value = "value") %>% 
  mutate(week = str_trunc(week, side = "left", 1, ellipsis = ""), 
         week = as.numeric(week)) %>% 
  ggplot(aes(x = week, y = value)) +
  geom_line(aes(color = subject), linetype = 1) +
  geom_smooth(aes(color = group), linetype = 3, se = FALSE) +
  labs(title = "Observations over time", 
       x = "Week", 
       y = "Observation") +
  theme_classic() 
```

The plot shows that there are some variations within each arm. The overall trend is that the observations of the treatment arm increase over time while the observations of the control arm decrease or remain the same over time. 

###Problem 2

####Load and tidy data
```{r load}
homi_data = read.csv("./data/problem2/homicide-data.csv") %>% 
  unite(city, state, col = "city_state", sep = ",")

total_homi =  
  homi_data %>% 
    group_by(city_state) %>% 
    summarize(homicide = n())

unsolved_homi = 
  homi_data %>% 
    filter(disposition == "Closed without arrest" | 
           disposition == "Open/No arrest") %>% 
    group_by(city_state) %>% 
    summarize(unsolved_homicide = n())  

sum_homi = left_join(total_homi, unsolved_homi, by = "city_state")
sum_homi %>% 
  replace_na(list(unsolved_homicide = 0)) %>% 
  knitr::kable()
```

